comtso_homepage:
    pattern:  /
    defaults: { _controller: ComTSoForumBundle:Home:index }

comtso_search:
    pattern:  /recherche
    defaults: { _controller: ComTSoForumBundle:Search:search }

comtso_chat:
    pattern:  /chat
    defaults: { _controller: ComTSoForumBundle:Chat:show }
    options:
        expose: true

comtso_forum:
    resource: "@ComTSoForumBundle/Resources/config/routing.forum.yml"

comtso_topic:
    resource: "@ComTSoForumBundle/Resources/config/routing.topic.yml"
    
comtso_comment:
    resource: "@ComTSoForumBundle/Resources/config/routing.comment.yml"
    
comtso_user:
    resource: "@ComTSoForumBundle/Resources/config/routing.user.yml"
    
comtso_photo:
    resource: "@ComTSoForumBundle/Resources/config/routing.photo.yml"
