
comtso_photo_show:
    pattern:  /photos/{id}
    defaults: { _controller: ComTSoForumBundle:Photo:show }
    requirements:
        id: "\d+"

comtso_photo_edit:
    pattern:  /photos/{id}/edit
    defaults: { _controller: ComTSoForumBundle:Photo:edit }
    requirements:
        id: "\d+"

comtso_photo_source_original:
    pattern:  /photos/source/{id}
    defaults: { _controller: ComTSoForumBundle:Photo:source }
    requirements:
        id: "\d+"

comtso_photo_backcompat:
    pattern:  /photos/{filter}/{originalFilename}
    defaults: { _controller: ComTSoForumBundle:Photo:sourceCache }
    requirements:
        originalFilename: "[a-z\d.]+"
        filter: "tiny|thumbnail|preview|large"

comtso_photo_source_cache:
    pattern:  /cache/{filter}/{filename}
    defaults: { _controller: ComTSoForumBundle:Photo:sourceCache }
    requirements:
        filename: "[a-z\d.]+"
        filter: "tiny|thumbnail|preview|large"

comtso_photo_update:
    pattern:  /api/photos/{id}
    defaults: { _controller: ComTSoForumBundle:Photo:update }
    options:
        expose: true

comtso_photo_browser:
    pattern: /photos/browser
    defaults: { _controller: ComTSoForumBundle:Photo:browser }
    options:
        expose: true

comtso_photo_uploader:
    pattern: /photos/uploader
    defaults: { _controller: ComTSoForumBundle:Photo:uploader }
    options:
        expose: true

comtso_photo_widget:
    pattern: /photos/{id}/widget
    defaults: { _controller: ComTSoForumBundle:Photo:widget }
    options:
        expose: true
