parameters:
    phpexiftool.reader.class: PHPExiftool\Reader

services:
    twig.extension.comtso_forum:
        class: ComTSo\ForumBundle\Twig\ForumExtension
        arguments:
            - @liip_imagine.filter.configuration
            - @comtso.config.handler
            - @router
            - @doctrine
            - %brand.name%
            - %owa.baseUrl%
            - %owa.siteId%
        tags:
            - { name: 'twig.extension' }

    comtso.image.uploader:
        class: ComTSo\ForumBundle\Service\ImageUploader
        arguments:
            - %comtso.photo_dir%
            - @doctrine
            - @liip_imagine
            - @phpexiftool.reader=
            - @security.token_storage
            - @router
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    phpexiftool.reader:
        scope: prototype
        class: "%phpexiftool.reader.class%"
        factory_class: "%phpexiftool.reader.class%"
        factory_method: create
        arguments:
            - "@logger"

    comtso.form.type.photo_selector:
        class: ComTSo\ForumBundle\Form\Type\PhotoSelectorType
        tags:
            - { name: form.type, alias: photo }

    comtso.config.handler:
        class: ComTSo\ForumBundle\Service\ConfigHandler
        calls:
            - [ setContainer, [ "@service_container" ] ]
