parameters:
    phpexiftool.reader.class: PHPExiftool\Reader

services:
    twig.extension.comtso_forum:
        class: ComTSo\ForumBundle\Twig\ForumExtension
        arguments: [ "@service_container" ]
        tags:
            - { name: 'twig.extension' }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            
    comtso.image.uploader:
        class: ComTSo\ForumBundle\Service\ImageUploader
        arguments: [ "@service_container" ]
        
    phpexiftool.reader:
        scope: prototype
        class: "%phpexiftool.reader.class%"
        factory_class: "%phpexiftool.reader.class%"
        factory_method: create
        arguments:
            - "@logger"