parameters:
    comtso.photo_dir: %kernel.data_dir%/photos
    comtso.search.repositories:
        comment:
            name: 'ComTSoForumBundle:Comment'
            label: Commentaires
        photo:
            name: 'ComTSoForumBundle:Photo'
            label: Photos
        chatmessage:
            name: 'ComTSoForumBundle:ChatMessage'
            label: Chats
        user:
            name: 'ComTSoUserBundle:User'
            label: Membres
        topic:
            name: 'ComTSoForumBundle:Topic'
            label: Topics
        quote:
            name: 'ComTSoForumBundle:Quote'
            label: Citations

joli_typo:
    presets:
        fr:
            fixers: [ Ellipsis, Dimension, Dash, FrenchQuotes, FrenchNoBreakSpace, CurlyQuote, Trademark ]
            locale: fr_FR
            
exercise_html_purifier:
    default:
      HTML.TargetBlank: true
#      AutoFormat.AutoParagraph: true
      AutoFormat.Linkify: true
      AutoFormat.RemoveEmpty: true
      AutoFormat.RemoveEmpty.RemoveNbsp: true
      AutoFormat.RemoveSpansWithoutAttributes: true
      Core.CollectErrors: false
#      HTML.AllowedElements:
#      HTML.AllowedAttributes:
      HTML.Trusted: true
      HTML.SafeIframe: true
      URI.SafeIframeRegexp: "\\^http://(www.youtube.com/embed/|player.vimeo.com/video/)\\"
      
liip_imagine:
    driver: %imagine_driver%
    resolvers:
       default:
          web_path:
            web_root: %comtso.photo_dir%
            cache_prefix: cache
    loaders:
        default:
            filesystem:
                data_root: %comtso.photo_dir%/originals
    filter_sets:
        tiny:
            quality: 70
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        thumbnail:
            quality: 70
            filters:
                thumbnail: { size: [165, 165], mode: outbound }
        preview:
            quality: 80
            filters:
                thumbnail: { size: [730, 730], mode: inset }
        large:
            quality: 90
            filters:
                thumbnail: { size: [1900, 1000], mode: inset }