<?php

namespace ComTSo\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function findLastCreatedSince(\DateTime $since, $limit = 50) {
		$qb = $this->createQueryBuilder('c')
				->where('c.createdAt > :since')
				->setParameter('since', $since)
				->addOrderBy('c.createdAt', 'DESC')
				->setMaxResults($limit);
		return $qb->getQuery()
						->getResult();
	}
	
	public function search($terms, $limit = 50) {
		$qb = $this->createQueryBuilder('c');
		$i = 0;
		foreach ($terms as $search) {
			$qb->andWhere("c.content LIKE :q{$i}")
					->setParameter("q{$i}", "%{$search}%");
			$i++;
		}
		$qb->addOrderBy('c.createdAt', 'DESC')
				->setMaxResults($limit);
		return $qb->getQuery()
						->getResult();
	}
}
