<?php

namespace ComTSo\ForumBundle\Entity;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends BaseRepository
{
    public function getQBForTopic(Topic $topic, $order = 'DESC')
    {
        $qb = $this->createQueryBuilder('e')
                ->where('e.topic = :topic')
                ->addOrderBy('e.createdAt', $order)
                ->setParameter('topic', $topic);

        return $qb;
    }
}
