<?php

namespace ComTSo\ForumBundle\Entity;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends BaseRepository
{
    public function findAll()
    {
        return $this->findBy([], ['order' => 'ASC']);
    }

}
