<?php

namespace ComTSo\ForumBundle\Entity;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends BaseRepository
{
}
