<?php

namespace ComTSo\ForumBundle\Entity;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoTopicRepository extends BaseRepository {
	
	public function findLast(Topic $topic) {
		$qb = $this->createQueryBuilder('e')
				->innerJoin('e.topic', 't')
				->where('t = :topic')
				->addOrderBy('e.order', 'DESC')
				->setMaxResults(1)
				->setParameter('topic', $topic);
		return $qb->getQuery()->getOneOrNullResult();
	}
}
