<?php

namespace ComTSo\ForumBundle\Entity;

use Doctrine\ORM\Query;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends BaseRepository {

	public function findRandom() {
		$count = $this->createQueryBuilder('q')
				->select('COUNT(q)')
				->getQuery()
				->getSingleResult(Query::HYDRATE_SINGLE_SCALAR);
		$qb = $this->createQueryBuilder('q')
				->setFirstResult(rand(0, $count - 1))
				->setMaxResults(1);
		return $qb->getQuery()
						->getSingleResult();
	}

	public function search($terms, $limit = 50) {
		$qb = $this->createQueryBuilder('q');
		$i = 0;
		foreach ($terms as $search) {
			$qb->andWhere("(q.content LIKE :q{$i} OR q.originalAuthor LIKE :qa{$i})")
					->setParameter("q{$i}", "%{$search}%")
					->setParameter("qa{$i}", "%{$search}%");
			$i++;
		}
		$qb->addOrderBy('q.createdAt', 'DESC')
				->setMaxResults($limit);
		return $qb->getQuery()
						->getResult();
	}

}
