<?php

namespace ComTSo\ForumBundle\Entity;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends BaseRepository
{
    public function findForForumList(Forum $forum)
    {
        $qb = $this->createQueryBuilder('e')
                ->leftJoin('e.photos', 'p')
                ->addSelect('p')
                ->where('e.forum = :forum')
                ->andWhere('p.order < 4 OR p.order IS NULL')
                ->addOrderBy('e.updatedAt', 'DESC')
                ->setParameter('forum', $forum);

        return $qb->getQuery()->getResult();
    }
}
